### ISSUE TITLE
Vs code is not finding ocean.json because it's using capital Ocean.json

### ISSUE THREAD

**Issue by rizerzero** [AlanLang/vscode-theme-ocean#9]
Installed pop os and then vscode, added the extension, but could not set the theme to ocean, I had this error message : 

Unable to load file:///home/novice/.var/app/com.visualstudio.code/data/vscode/extensions/alanlang.theme-ocean-0.5.0/themes/ocean.json

The reason being the file ocean.json was named Ocean.json 

Thank you for sharing the theme by the way.

**Comment by AlanLang** [comment]
thank you
https://github.com/AlanLang/vscode-theme-ocean/commit/f565a605b71ed5db0dd722b79f68bc503b8bfd9c
